### ISSUE TITLE
Chyby při obohacování z NDK

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Kramerius-plus#29]
Titul: `uuid:9d73aa50-4083-11ed-80d2-5ef3fc9bb22f`

Chyba: `
javax.xml.bind.DataBindingException: javax.xml.bind.UnmarshalException - with linked exception: [org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 66; Element type "premis:formatRegistry" must be followed by either attribute specifications, ">" or "/>".] at javax.xml.bind.JAXB.unmarshal(JAXB.java:230)`

Poznámka: na tuto chybu jsem narazil nedávno u jiného projektu, příčinou bylo to, že soubor XML obsahoval místo znaků pro lomítka ap. nějaké entity. Možná je tedy chyba ve zdrojových datech NDK.

Titul: `uuid:c3582e30-4079-11ed-80d2-5ef3fc9bb22f`

Chyba: `
javax.xml.bind.DataBindingException: javax.xml.bind.UnmarshalException - with linked exception: [org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.] at javax.xml.bind.JAXB.unmarshal(JAXB.java:230) at cz.inqool.dl4dh.krameriusplus.service.system.enricher.page.mets.mappers.PremisObjectMapper.map(PremisObjectMapper.java:24)`

**Comment by daliboris** [comment]
Všechny úlohy doběhly bet problémů.
